name: Release on tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: The tag to check out
        required: true

jobs:
  test:
    uses: ./.github/workflows/tests.yaml
  getversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.pkgVersion }}
    steps:
      - name: Get version
        id: get_version
        run: |
          version=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]
          then
            version="${{ github.event.inputs.version }}"
          else
            version="$GITHUB_REF_NAME"
          fi
          echo "pkgVersion=$version" >> $GITHUB_OUTPUT
          echo "Version: $version"
  build:
    needs: [test, getversion]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.getversion.outputs.version }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Build
        run: |
          python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            dist/screen_brightness_control*.whl
            dist/screen_brightness_control*.tar.gz
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: packages
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "dist/*"
          name: "${{ needs.getversion.outputs.version }}"
          tag_name: ${{ needs.getversion.outputs.version }}
