name: Tests
on:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - screen_brightness_control/**
      - docs/**
      - tests/**
      - .github/**
    tags-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.9"]
        os:
          - ubuntu-latest
          - windows-latest
        exclude:
          - os: windows-latest
            python-version: 'pypy3.9'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flake8
          python -m pip install .
      - name: Lint with flake8
        run: |
          flake8 screen_brightness_control --max-line-length=119 --ignore=W503
      - name: Run tests
        run: |
          python tests/testall.py --synthetic
